@push('styles')
<link rel="stylesheet" href="{{ asset('xlink-network-monitoring/network-monitoring-polish.css') }}">
<link rel="stylesheet" href="{{ asset('xlink-network-monitoring/network-map-polish.css') }}">
<style>#network-map{min-height:650px;border-radius:12px;overflow:hidden}.network-map-google-status{min-height:650px;display:flex;align-items:center;justify-content:center;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px}</style>
@endpush
<div class="container-fluid py-3 network-map-page">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h3 class="mb-1"><i class="bi bi-diagram-3 me-2"></i>Network Map</h3><small class="text-muted">Geographic view of routers, OLT/ONU devices, access points and mapped customers</small></div><div class="d-flex align-items-center gap-2"><span class="badge bg-success">{{ $routers->where('action','connected')->count() }} routers online</span><a class="btn btn-sm btn-outline-primary" href="{{ route('network-topology.live') }}"><i class="bi bi-diagram-3 me-1"></i>Live Topology</a></div></div>
<div class="row g-3 mb-3">
<div class="col-md-3"><div class="card map-stat-card"><div class="card-body"><small>Active Customers</small><h4>{{ number_format($customers) }}</h4><span class="text-muted small">Billing accounts</span></div></div></div>
<div class="col-md-3"><div class="card map-stat-card"><div class="card-body"><small>Mapped Nodes</small><h4>{{ number_format($nodes->count()) }}</h4><span class="text-muted small">With valid coordinates</span></div></div></div>
<div class="col-md-6"><div class="card map-stat-card"><div class="card-body"><div class="map-device-legend"><span><i class="map-legend-dot router"></i>MikroTik</span><span><i class="map-legend-dot olt"></i>OLT</span><span><i class="map-legend-dot onu"></i>ONU</span><span><i class="map-legend-dot wifi-router"></i>WiFi</span><span><i class="map-legend-dot access-point"></i>AP</span><span><i class="map-legend-dot customer"></i>Customer</span></div></div></div></div>
</div>
<div class="card"><div class="card-body">
<div class="row g-2 mb-3">
<div class="col-lg-3 col-md-6"><label class="form-label">Device / Network Type</label><select id="map-type-filter" class="form-select"><option value="">All Devices</option><option value="router">MikroTik Router</option><option value="olt">OLT</option><option value="onu">ONU</option><option value="wifi-router">WiFi Router</option><option value="access-point">Access Point</option><option value="switch">Switch</option><option value="customer">Customer</option></select></div>
<div class="col-lg-3 col-md-6"><label class="form-label">Router</label><select id="map-router-filter" class="form-select"><option value="">All Routers</option>@foreach($routers as $r)<option value="{{ $r->router_name }}">{{ $r->router_name }}</option>@endforeach</select></div>
<div class="col-lg-2 col-md-6"><label class="form-label">Status</label><select id="map-status-filter" class="form-select"><option value="">All Status</option><option value="online">Online</option><option value="offline">Offline</option><option value="unknown">Unknown</option></select></div>
<div class="col-lg-4 col-md-6"><label class="form-label">Search</label><div class="input-group"><input id="map-customer-search" class="form-control" placeholder="Name, IP, ID or location"><button id="map-fit" class="btn btn-outline-secondary" type="button" title="Fit visible nodes"><i class="bi bi-bounding-box"></i></button><button id="map-reset" class="btn btn-outline-secondary" type="button" title="Reset filters"><i class="bi bi-arrow-counterclockwise"></i></button></div></div>
</div>
<div id="network-map" class="network-map-canvas" aria-label="Interactive Google network map"></div>
<div class="network-map-footer"><span><i class="bi bi-info-circle me-1"></i>Markers are based on stored coordinates. Connections appear only when both endpoints have coordinates.</span><span id="map-result-count"></span></div>
</div></div>
</div>
<script>
(() => {
 const apiKey=@json(config('services.google_maps.api_key'));
 const mapId=@json(config('services.google_maps.map_id'));
 const nodes=@json($nodes), edges=@json($mapEdges);
 const meta={router:['MikroTik Router','router'],olt:['OLT','olt'],onu:['ONU','onu'],'wifi-router':['WiFi Router','wifi-router'],'access-point':['Access Point','access-point'],switch:['Switch','switch'],customer:['Customer','customer']};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const loadGoogle=()=>new Promise((resolve,reject)=>{if(window.google?.maps)return resolve();if(!apiKey)return reject(new Error('GOOGLE_MAPS_API_KEY is not configured'));window.__xlinkGoogleMapsReady=resolve;window.gm_authFailure=()=>reject(new Error('Google Maps authentication failed: check API key, billing, API restrictions and allowed referrers.'));const s=document.createElement('script');s.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(apiKey)+'&loading=async&callback=__xlinkGoogleMapsReady&libraries=geometry';s.async=true;s.defer=true;s.onerror=()=>reject(new Error('Google Maps API failed to load'));document.head.appendChild(s);});
 window.initNetworkMap=async()=>{const el=document.getElementById('network-map');if(!el||el._googleMap)return;try{await loadGoogle();}catch(e){console.error('[X-Link Network Map] Google Maps:',e);el.innerHTML='<div class="network-map-google-status"><div class="text-center p-4"><i class="bi bi-map fs-1 text-primary"></i><h5 class="mt-3">Google Maps could not load</h5><p class="text-muted mb-0">'+esc(e.message||'Google Maps API error')+'</p><small class="text-muted d-block mt-2">Check Google Cloud API, billing and HTTP referrer restrictions.</small></div></div>';return;}
 const map=new google.maps.Map(el,{center:{lat:23.8103,lng:90.4125},zoom:11,mapTypeControl:true,streetViewControl:true,fullscreenControl:true,zoomControl:true,mapId:mapId||undefined});el._googleMap=map;
 let markers=[],lines=[];
 const clear=()=>{markers.forEach(m=>m.setMap(null));lines.forEach(l=>l.setMap(null));markers=[];lines=[];};
 const fit=pts=>{if(!pts.length){map.setCenter({lat:23.8103,lng:90.4125});map.setZoom(11);return;}const bounds=new google.maps.LatLngBounds();pts.forEach(p=>bounds.extend(p));map.fitBounds(bounds);if(pts.length===1)map.setZoom(15);};
 const render=()=>{clear();const tf=document.getElementById('map-type-filter')?.value||'',rf=document.getElementById('map-router-filter')?.value||'',sf=document.getElementById('map-status-filter')?.value||'',q=(document.getElementById('map-customer-search')?.value||'').toLowerCase().trim();const filtered=nodes.filter(n=>(!tf||n.kind===tf)&&(!rf||n.router===rf)&&(!sf||n.status===sf)&&(!q||[n.id,n.label,n.ip,n.location,n.kind].some(v=>String(v??'').toLowerCase().includes(q))));const visibleKeys=new Set(filtered.map(n=>(n.kind==='router'?'router:':'device:')+n.id);
 edges.forEach(e=>{if(e.fromKey&&e.toKey&&(!visibleKeys.has(e.fromKey)||!visibleKeys.has(e.toKey)))return;const line=new google.maps.Polyline({path:[{lat:e.from[0],lng:e.from[1]},{lat:e.to[0],lng:e.to[1]}],geodesic:true,strokeColor:e.type==='logical_service'?'#2563eb':'#16a34a',strokeOpacity:.7,strokeWeight:e.type==='logical_service'?3:4,map});line.setOptions({icons:e.type==='logical_service'?[{icon:{path:'M 0,-1 0,1',strokeOpacity:1,scale:3},offset:'0',repeat:'16px'}]:[]});line.addListener('click',()=>{const info=new google.maps.InfoWindow({content:'<strong>'+esc(e.label)+'</strong><div>'+esc(e.type)+'</div>'});info.setPosition({lat:e.from[0],lng:e.from[1]});info.open({map});});lines.push(line);});
 const pts=[];filtered.forEach(n=>{const mta=meta[n.kind]||['Device','device'];const marker=new google.maps.Marker({position:{lat:n.lat,lng:n.lng},map,title:n.label||mta[0],label:{text:mta[0].charAt(0),color:'#fff',fontWeight:'700'},optimized:true});const popup=new google.maps.InfoWindow({content:'<div style="min-width:190px"><strong>'+esc(mta[0])+'</strong><div>'+esc(n.label)+'</div><small>IP: '+esc(n.ip||'—')+'</small><br><small>Status: '+esc(n.status||'unknown')+'</small><br><small>'+esc(n.location||'')+'</small></div>'});marker.addListener('click',()=>popup.open({map,anchor:marker}));markers.push(marker);pts.push({lat:n.lat,lng:n.lng});});document.getElementById('map-result-count').textContent=filtered.length+' node'+(filtered.length===1?'':'s')+' shown';fit(pts);};
 ['map-type-filter','map-router-filter','map-status-filter'].forEach(id=>document.getElementById(id)?.addEventListener('change',render));document.getElementById('map-customer-search')?.addEventListener('input',render);document.getElementById('map-fit')?.addEventListener('click',render);document.getElementById('map-reset')?.addEventListener('click',()=>{['map-type-filter','map-router-filter','map-status-filter'].forEach(id=>document.getElementById(id).value='');document.getElementById('map-customer-search').value='';render();});render();};
 document.addEventListener('livewire:navigated',()=>window.initNetworkMap?.());if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.initNetworkMap?.());else window.initNetworkMap?.();
})();
</script>
