<x-app-layout>
<div class="container-fluid px-1">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="mb-1"><i class="bi bi-chat-dots me-2"></i>Communication Center</h3><div class="text-muted">Chat, SMS, notifications and WhatsApp communication controls.</div></div><span class="badge bg-success-subtle text-success">Live</span></div>
<div class="d-flex flex-wrap gap-2 mb-3"><a class="btn btn-sm {{($tab??'dashboard')==='dashboard'?'btn-primary':'btn-outline-primary'}}" href="{{route('xlink.communication-center')}}">Overview</a><a class="btn btn-sm {{($tab??'')==='chat'?'btn-primary':'btn-outline-primary'}}" href="{{route('communication-center.chat')}}">Chat</a><a class="btn btn-sm {{($tab??'')==='settings'?'btn-primary':'btn-outline-primary'}}" href="{{route('communication-center.settings')}}">Communication Settings</a><a class="btn btn-sm {{($tab??'')==='whatsapp'?'btn-primary':'btn-outline-primary'}}" href="{{route('communication-center.whatsapp')}}">WhatsApp Inbox</a><a class="btn btn-sm btn-outline-secondary" href="{{route('sms-setup')}}">SMS Setup</a><a class="btn btn-sm btn-outline-secondary" href="{{route('sms-bridge.index')}}">SMS Bridge</a><a class="btn btn-sm btn-outline-secondary" href="{{route('notifications')}}">Notifications</a></div>
@if(session('communication_message'))<div class="alert alert-success">{{session('communication_message')}}</div>@endif
@if(($tab??'dashboard')==='dashboard')
<div class="row g-3 mb-4">@foreach($stats as $x)<div class="col-md-4"><div class="card shadow-sm h-100"><div class="card-body"><small class="text-muted">{{$x['label']}}</small><div class="fs-3 fw-bold mt-2">{{$x['value']}}</div></div></div></div>@endforeach</div>
<div class="row g-3"><div class="col-xl-4"><div class="card shadow-sm h-100"><div class="card-body"><h5 class="fw-bold">Chat</h5><p class="text-muted">Customer conversations are connected to the existing support-ticket workflow.</p><a class="btn btn-primary" href="{{route('communication-center.chat')}}">Open Chat</a></div></div></div><div class="col-xl-4"><div class="card shadow-sm h-100"><div class="card-body"><h5 class="fw-bold">Messaging</h5><p class="text-muted">Configure the existing SMS gateway and bridge without changing the production SMS flow.</p><a class="btn btn-outline-primary me-1" href="{{route('sms-setup')}}">SMS Setup</a><a class="btn btn-outline-primary" href="{{route('sms-bridge.index')}}">SMS Bridge</a></div></div></div><div class="col-xl-4"><div class="card shadow-sm h-100"><div class="card-body"><h5 class="fw-bold">WhatsApp Inbox</h5><p class="text-muted">Inbox view uses the support conversation stream until a dedicated WhatsApp API connector is enabled.</p><a class="btn btn-outline-primary" href="{{route('communication-center.whatsapp')}}">Open Inbox</a></div></div></div></div>
@elseif(($tab??'')==='chat' || ($tab??'')==='whatsapp')
<div class="card shadow-sm"><div class="card-header fw-bold">{{($tab==='chat')?'Customer Chat':'WhatsApp Inbox'}}</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Ticket</th><th>Customer</th><th>Subject</th><th>Category</th><th>Status</th><th>Priority</th><th>Updated</th></tr></thead><tbody>@forelse($tickets as $t)<tr><td><code>{{$t->ticket_no}}</code></td><td>{{optional($t->customer)->name ?? $t->customer_unique_id}}</td><td>{{$t->subject}}</td><td>{{$t->category?:'—'}}</td><td><span class="badge bg-secondary">{{$t->status}}</span></td><td><span class="badge bg-light text-dark">{{$t->priority}}</span></td><td>{{$t->updated_at?->diffForHumans()}}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No conversations found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{$tickets->links()}}</div></div>
@else
<div class="row g-3"><div class="col-xl-7"><div class="card shadow-sm"><div class="card-header fw-bold">Communication Settings</div><div class="card-body"><form method="POST" action="{{route('communication-center.settings.update')}}">@csrf<div class="mb-3"><label class="form-label">WhatsApp Business Number</label><input name="whatsapp" class="form-control" value="{{$whatsapp??''}}" placeholder="8801XXXXXXXXX"></div><div class="mb-3"><label class="form-label">Notification Email</label><input type="email" name="notification_email" class="form-control" placeholder="noc@example.com"></div><div class="mb-3"><label class="form-label">Notification Destination URL</label><input type="url" name="notification_url" class="form-control" placeholder="https://..."></div><button class="btn btn-primary">Save Communication Settings</button></form></div></div></div><div class="col-xl-5"><div class="card shadow-sm"><div class="card-body"><h5 class="fw-bold">Existing Production Channels</h5><div class="list-group list-group-flush"><a class="list-group-item list-group-item-action" href="{{route('sms-setup')}}">SMS Setup <span class="float-end">→</span></a><a class="list-group-item list-group-item-action" href="{{route('sms-bridge.index')}}">SMS Bridge <span class="float-end">→</span></a><a class="list-group-item list-group-item-action" href="{{route('notifications')}}">Notifications <span class="float-end">→</span></a></div></div></div></div></div>
@endif
</div>
</x-app-layout>
