<x-app-layout>
@push('styles')<link rel="stylesheet" href="{{ asset('xlink-olt/olt-source.css') }}">@endpush
<div class="d-flex justify-content-between align-items-center mb-3"><div><span class="text-uppercase small text-muted fw-semibold">Admin Panel</span><h3 class="mb-0">OLT Customers / ONU</h3><small class="text-muted">{{ $device->name }} · {{ $device->ip_address ?: $device->host ?: 'No IP' }}</small></div><a class="btn btn-outline-secondary" href="{{ route('network-inventory.olt') }}">Back to OLT</a></div>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="card"><div class="card-body"><small>Live ONU Total</small><h4>{{ count($live['onus'] ?? []) }}</h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small>Live Online</small><h4 class="text-success">{{ collect($live['onus'] ?? [])->where('status','online')->count() }}</h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small>Mapped Customers</small><h4>{{ $mappings->whereNotNull('customer_id')->count() }}</h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small>Mapped PPPoE</small><h4>{{ $mappings->whereNotNull('ppp_user_id')->count() }}</h4></div></div></div></div>
<div class="card shadow-sm mb-3"><div class="card-body"><form method="GET" class="row g-2"><div class="col-md-7"><input class="form-control" name="q" value="{{ $q ?? '' }}" placeholder="Search customer, PPPoE, ONU ID, serial, MAC or PON"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All Status</option><option value="online" @selected(($status ?? '')==='online')>Online</option><option value="offline" @selected(($status ?? '')==='offline')>Offline</option><option value="unknown" @selected(($status ?? '')==='unknown')>Unknown</option></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary flex-fill">Search</button><a class="btn btn-outline-secondary" href="{{ route('network-inventory.olt.customers',$device) }}">Reset</a></div></form></div></div>
<div class="card shadow-sm mb-3"><div class="card-header d-flex justify-content-between align-items-center"><strong>Live ONU Telemetry</strong><span class="text-muted small">Read-only · refreshed on page load</span></div><div class="card-body p-0">@if(!empty($live['error']))<div class="alert alert-warning m-3 mb-0">Live telemetry error: {{ $live['error'] }}</div>@elseif(($live['status'] ?? '')==='ok')<div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>ONU ID</th><th>PON</th><th>MAC</th><th>Status</th></tr></thead><tbody>@forelse(($live['onus'] ?? []) as $onu)<tr><td>{{ $onu['onu_id'] ?? '—' }}</td><td>{{ $onu['pon_port'] ?? '—' }}</td><td>{{ $onu['onu_mac'] ?? '—' }}</td><td><span class="badge {{ ($onu['status'] ?? '')==='online'?'bg-success':(($onu['status'] ?? '')==='offline'?'bg-danger':'bg-secondary') }}">{{ ucfirst($onu['status'] ?? 'unknown') }}</span></td></tr>@empty<tr><td colspan="4" class="text-center py-4 text-muted">No live ONU telemetry returned.</td></tr>@endforelse</tbody></table></div>@else<div class="p-3 text-muted">Live telemetry unavailable.</div>@endif</div></div>
@if(session('inventory_message'))<div class="alert alert-success">{{ session('inventory_message') }}</div>@endif
@if(($live['status'] ?? '')==='ok')
<div class="card shadow-sm mb-3"><div class="card-header"><strong>Manual ONU → Customer / PPPoE Mapping</strong><small class="d-block text-muted">Choose the customer explicitly. Saving records a mapping only; it does not change the OLT or MikroTik.</small></div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>ONU</th><th>MAC / PON</th><th>Live status</th><th>Customer + PPPoE</th><th>Action</th></tr></thead><tbody>
@forelse(($live['onus'] ?? []) as $onu)
@php($onuId=(string)($onu['onu_id'] ?? ''))
@php($saved=$mappingByOnu->get($onuId))
<tr><td>{{ $onuId !== '' ? $onuId : '—' }}</td><td>{{ $onu['onu_mac'] ?? '—' }}<small class="d-block text-muted">PON {{ $onu['pon_port'] ?? '—' }}</small></td><td>{{ ucfirst($onu['status'] ?? 'unknown') }}</td><td><form method="POST" action="{{ route('network-inventory.olt.customers.mapping',$device) }}" id="onu-map-{{ $loop->index }}">@csrf<input type="hidden" name="onu_id" value="{{ $onuId }}"><input type="hidden" name="onu_mac" value="{{ $onu['onu_mac'] ?? '' }}"><input type="hidden" name="pon_port" value="{{ $onu['pon_port'] ?? '' }}"><select class="form-select form-select-sm" name="customer_id" required><option value="">Select customer / PPPoE</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)($saved->customer_id ?? '')===(string)$customer->id)>{{ $customer->customer_name ?: $customer->customer_unique_id }} — {{ $customer->pppUser->username ?? 'No PPPoE' }}</option>@endforeach</select>@php($candidate=$matchingCandidates[(string)($saved->id ?? '')] ?? null)
@if($candidate && !empty($candidate["candidate"]) && empty($saved?->customer_id))<div class="alert alert-info py-2 px-2 mt-2 mb-0 small"><strong>সম্ভাব্য Customer:</strong> {{ $candidate["candidate"]["customer_name"] ?? $candidate["candidate"]["customer_id"] }} · {{ $candidate["candidate"]["customer_id"] ?? '' }} · {{ $candidate["candidate"]["score"] ?? 0 }}%<br><span>{{ implode(" · ", $candidate["candidate"]["reasons"] ?? []) }}</span></div>@endif@if($saved)<label class="small text-warning mt-1"><input type="checkbox" name="confirm_overwrite" value="1" required> Confirm replacing existing mapping</label>@endif</form></td><td><button class="btn btn-sm btn-primary" type="submit" form="onu-map-{{ $loop->index }}">Save mapping</button>@if($saved)<small class="d-block text-muted">Currently mapped</small>@endif</td></tr>
@empty<tr><td colspan="5" class="text-center py-3 text-muted">No live ONU rows available.</td></tr>@endforelse
</tbody></table></div></div></div>
@endif
<div class="card shadow-sm mb-3">
<div class="card-header d-flex justify-content-between align-items-center"><strong>Needs Review / Unmapped ONU</strong><span class="badge bg-warning text-dark">{{ $mappings->whereNull('customer_id')->count() }}</span></div>
<div class="card-body p-0">
@if($mappings->whereNull('customer_id')->count())
<div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>ONU</th><th>MAC / Serial</th><th>PON</th><th>Status</th><th>RX / TX</th><th>Reason</th><th>Action</th></tr></thead><tbody>
@foreach($mappings->whereNull('customer_id') as $review)
<tr>
<td><strong>{{ $review->onu_id !== null && $review->onu_id !== '' ? $review->onu_id : '—' }}</strong></td>
<td>{{ $review->onu_mac ?: '—' }}<small class="d-block text-muted">{{ $review->onu_serial ?: '—' }}</small></td>
<td>{{ $review->pon_port !== null && $review->pon_port !== '' ? $review->pon_port : '—' }}</td>
<td><span class="badge {{ $review->status==='online'?'bg-success':($review->status==='offline'?'bg-danger':'bg-secondary') }}">{{ ucfirst($review->status) }}</span></td>
<td>{{ $review->rx_power !== null ? $review->rx_power.' dBm' : '—' }} / {{ $review->tx_power !== null ? $review->tx_power.' dBm' : '—' }}</td>
<td>@php($candidate=$matchingCandidates[(string)$review->id] ?? null)
@if($candidate && !empty($candidate["candidate"]))<span class="badge bg-info text-dark">সম্ভাব্য মিল {{ $candidate["candidate"]["score"] ?? 0 }}%</span><small class="d-block text-muted">{{ implode(" · ", $candidate["candidate"]["reasons"] ?? []) }}</small>@else<span class="text-muted small">কোনও নির্ভরযোগ্য মিল পাওয়া যায়নি; ম্যানুয়াল যাচাই প্রয়োজন।</span>@endif</td>
<td><a class="btn btn-sm btn-outline-primary" href="{{ route('network-inventory.olt.customers',$device,['q'=>$review->onu_id]) }}">Review / Map</a></td>
</tr>
@endforeach
</tbody></table></div>
@else
<div class="p-3 text-success">All discovered ONU rows are currently mapped.</div>
@endif
</div></div>
<div class="card shadow-sm"><div class="card-header d-flex justify-content-between align-items-center"><strong>ONU / Customer Mappings</strong><span class="text-muted small">{{ $mappings->count() }} result(s)</span></div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Customer</th><th>PPPoE</th><th>ONU ID</th><th>Serial / MAC</th><th>PON</th><th>Status</th><th>RX / TX</th><th>Last Seen</th></tr></thead><tbody>
@forelse($mappings as $m)<tr><td><strong>{{ optional($m->customer)->customer_name ?: optional($m->customer)->customer_unique_id ?: 'Unmapped' }}</strong><small class="d-block text-muted">{{ optional($m->customer)->mobile }}</small></td><td>{{ optional($m->pppUser)->username ?: '—' }}</td><td>{{ $m->onu_id !== null && $m->onu_id !== '' ? $m->onu_id : '—' }}</td><td>{{ $m->onu_serial ?: '—' }}<small class="d-block text-muted">{{ $m->onu_mac ?: '' }}</small></td><td>{{ $m->pon_port !== null && $m->pon_port !== '' ? $m->pon_port : '—' }}</td><td><span class="badge {{ $m->status==='online'?'bg-success':($m->status==='offline'?'bg-danger':'bg-secondary') }}">{{ ucfirst($m->status) }}</span></td><td>{{ $m->rx_power !== null ? $m->rx_power.' dBm' : '—' }} / {{ $m->tx_power !== null ? $m->tx_power.' dBm' : '—' }}</td><td>{{ optional($m->last_seen_at)->format('d M Y H:i:s') ?: '—' }}</td></tr>@empty<tr><td colspan="8" class="text-center py-5 text-muted">No customer mappings are saved yet. Live ONU telemetry is shown above; mapping records remain separate.</td></tr>@endforelse
</tbody></table></div></div></div>
</x-app-layout>
