<x-app-layout>
<div class="container-fluid px-2"><div class="d-flex justify-content-between align-items-center mb-3"><div><span class="text-muted small">Admin Panel / OLT / Provisioning</span><h3 class="mb-0">{{ $device->name }}</h3><small>{{ $device->vendor }} · {{ $device->model ?: 'Model not set' }} · {{ $device->ip_address }}</small></div><div><a class="btn btn-outline-secondary" href="{{ route('network-inventory.olt') }}">Back</a> <a class="btn btn-outline-primary" href="{{ route('network-inventory.olt.customers',$device) }}">ONU Customers</a></div></div>
@if(session('provisioning_message'))<div class="alert alert-success">{{ session('provisioning_message') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="alert alert-warning py-2"><strong>Exact model lock:</strong> live commands require an exact model/profile match. Passwords are excluded from the audit payload.</div>
<form method="POST" action="{{ route('network-inventory.olt.provision',$device) }}" class="row g-3">@csrf
<div class="col-md-4"><label class="form-label">VSOL command profile</label><select name="profile" class="form-select" required>@foreach($profiles as $key=>$p)<option value="{{ $key }}" @selected($selected===$key)>{{ $p['label'] }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Action</label><select name="action" id="vsolAction" class="form-select" required><option value="authorize_mac">Authorize MAC</option><option value="remove_mac">Remove MAC</option><option value="configure_pppoe">Configure PPPoE</option><option value="configure_static_ip">Configure Static IP</option><option value="enable_onu">Enable ONU</option><option value="disable_onu">Disable ONU</option></select></div>
<div class="col-md-2"><label class="form-label">PON</label><input name="pon" class="form-control" placeholder="0/1" required></div><div class="col-md-2"><label class="form-label">ONU ID</label><input name="onu" class="form-control"></div>
<div class="col-md-4" data-field="mac"><label class="form-label">ONU MAC</label><input name="mac" class="form-control" placeholder="AA:BB:CC:DD:EE:FF"></div>
<div class="col-md-4" data-field="pppoe"><label class="form-label">PPPoE Username</label><input name="username" class="form-control"></div><div class="col-md-4" data-field="pppoe"><label class="form-label">PPPoE Password</label><input type="password" name="password" class="form-control" autocomplete="new-password"></div><div class="col-md-4" data-field="pppoe"><label class="form-label">PPPoE Server</label><input name="server" class="form-control"></div>
<div class="col-md-3" data-field="static"><label class="form-label">IP</label><input name="ip" class="form-control"></div><div class="col-md-3" data-field="static"><label class="form-label">Netmask</label><input name="netmask" class="form-control"></div><div class="col-md-3" data-field="static"><label class="form-label">Gateway</label><input name="gateway" class="form-control"></div><div class="col-md-3" data-field="static"><label class="form-label">DNS 1</label><input name="dns1" class="form-control"></div><div class="col-md-3" data-field="static"><label class="form-label">DNS 2</label><input name="dns2" class="form-control"></div>
<div class="col-12"><button class="btn btn-primary" onclick="return confirm('Send this provisioning command to the selected OLT?')">Execute provisioning</button></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-header"><strong>Provisioning Audit Log</strong> <span class="float-end">{{ $audits->total() }} records</span></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Time</th><th>Action</th><th>Target</th><th>Profile</th><th>Status</th><th>Duration</th><th>Result/Error</th></tr></thead><tbody>@forelse($audits as $a)<tr><td>{{ $a->created_at }}</td><td>{{ $a->action }}</td><td>{{ $a->target }}</td><td>{{ $a->model_profile }}</td><td><span class="badge {{ $a->status==='success'?'bg-success':($a->status==='failed'?'bg-danger':'bg-warning') }}">{{ $a->status }}</span></td><td>{{ $a->duration_ms }} ms</td><td class="small text-break">{{ $a->status==='success'?$a->result:$a->error }}</td></tr>@empty<tr><td colspan="7" class="text-center py-4">No provisioning attempts yet.</td></tr>@endforelse</tbody></table></div><div class="p-2">{{ $audits->links() }}</div></div></div>
<script>(function(){function s(){let a=document.getElementById('vsolAction').value;document.querySelectorAll('[data-field]').forEach(e=>e.style.display='none');let m={authorize_mac:['mac'],remove_mac:['mac'],configure_pppoe:['pppoe'],configure_static_ip:['static'],enable_onu:[],disable_onu:[]};(m[a]||[]).forEach(k=>document.querySelectorAll('[data-field='+k+']').forEach(e=>e.style.display='block'));document.querySelector('input[name=onu]').required=['configure_pppoe','configure_static_ip','enable_onu','disable_onu'].includes(a);document.querySelector('input[name=mac]').required=['authorize_mac','remove_mac'].includes(a)}document.getElementById('vsolAction').addEventListener('change',s);s()})();</script>
</x-app-layout>